# Part 1: Numpy

In this part of the homework, we will use `Numpy` for multiple tasks

In [15]:
# this cell imports all the necessary package for this notebook
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import linalg

---
According to wikipedia, a graph is a structure that represents connections between *vertices* or *nodes* through *edges*. These edges represent relationships. For example, the social structure Anna is a friend of Bob, and Bob is a friend of Charles, and Charles is a friend of Anna can be represented by three nodes A, B, and C and three edges connecting A $\rightarrow$ B, B $\rightarrow$ C, and C $\rightarrow$ A.

We can represent a graph using Numpy arrays. In particular, we will represent a graph as a matrix such that the entry $a_{ij}$ will be 1 if there is a connection between the node $i$ and $j$, and 0 otherwise. This matrix is sometimes called the [Adjacency matrix](https://en.wikipedia.org/wiki/Adjacency_matrix).

In a Numpy representation of a graph, we will assume that an $n$ by $n$ matrix $A$ represents the connectivity between nodes 0, 1, 2, $\dots$, and $n-1$. In this way, the following matrix

$$ 
A = \left(\begin{array}{cc}
0 & 1 & 0\\
0 & 0 & 1\\
1 & 0 & 0\\
\end{array}\right)
$$

represents the graph previously described where Anna is node 0, Bob is node 1, and Charles is node 1.

## Question 1.1:  (15 pts)

Constructing interesting graphs can sometimes be done by defining a function `f(i,j)` that produces a 1 if there is an edge between node `i` and `j` and 0 if there is not an edge. Create a function `create_graph(f, n)` that returns a Numpy matrix with the adjancency matrix defined by the function `f` for $i\in(0, \dots, n-1)$ and $j \in (0, \dots, n-1)$

For example, for the following function

```python
def self_connections_only(i, j):
    if i == j:
        return 1
    else:
        return 0
```

the call to `create_matrix(self_connections_only, 4)` should create the following adjacency matrix

```python
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])
```

**Hint: Use list comprehension to evaluate the possible values of `f(i, j)` and then convert into a Numpy matrix**

In [16]:
def create_matrix(f, n):
    x = [0]*n*n
    x =  np.array(x)
    x = x.reshape(n,n)
    for i in range(n):
        for j in range(n):
            x[i][j]= f(i,j)
    return x
    # YOUR CODE HERE
    #raise NotImplementedError()

In [17]:
def self_connections_only(i, j):
    if i == j:
        return 1
    else:
        return 0

In [18]:
# test the function or define your own function
create_matrix(self_connections_only, 4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
assert create_matrix(self_connections_only, 10).sum() == 10
assert create_matrix(self_connections_only, 100).sum() == 100

def upper_triangular(i, j):
    if j>=i:
        return 1
    else:
        return 0
# testing a range of matrices
for i in range(1, 10):
    np.testing.assert_almost_equal(create_matrix(upper_triangular, i).sum(axis=0), np.arange(1, i+1, 1))
    

## Question 1.2: (35 pts)

There are several quantitites that we would like to compute about graphs. In this question, I will ask you to define functions that return these quantities.

**All these quantities must be computed using Numpy arrays**

### Incoming connections

Define a function that returns the average number of incoming connections to nodes.
For example, for the following graph:

$$ 
A = \left(\begin{array}{cc}
0 & 1 & 1\\
0 & 0 & 1\\
0 & 0 & 0\\
\end{array}\right)
$$

The average number of incoming connections is $\frac{0 + 1 + 2}{3} = 1$

In [20]:
# 10 points
def avg_incoming_connections(A):
    result = 0
    for i in range(len(A)):
        result = result + A[i].sum()
    result = result/len(A)
    return result
    #raise NotImplementedError()
    
#the result can also be achieved with below code:
#def avg_incoming_connections(A):
#    return A.sum()/len(A)
#The first code was chosen to elaborate the logic behind counting number of incoming connections


In [21]:
A = np.array([[0, 1, 1], [0, 0, 1], [0, 0, 0]])
np.testing.assert_almost_equal(avg_incoming_connections(A), 1)

bA = np.array([[1, 0, 0, 0, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0]])
np.testing.assert_almost_equal(avg_incoming_connections(bA), 2.3999999999999999)



### Self to outward connection difference

From an adjancency matrix, compute the total number of self-connections ($s$) and the total number of non-self-connections ($o$). And compute the following quantity

$$d = \log(s) - \log(o)$$

For the following graph

$$ 
A = \left(\begin{array}{cc}
1 & 1 & 1\\
0 & 0 & 1\\
1 & 0 & 0\\
\end{array}\right)
$$

$s = 1$ and $o = 4$ therefore $d = \log(1) - \log(4) = -1.386$ Define the function with the name `connection_difference(A)`

In [22]:
# 10 points
import math
def connection_difference(A):
    result_S = 0
    for i in range(len(A)):
        for j in range(len(A)):
            if (A[i][j]==1 and i==j):
                result_S = result_S + 1
    result_O = A.sum()-result_S
    d = math.log(result_S) - math.log(result_O)
    return d
    # YOUR CODE HERE
    #raise NotImplementedError()

In [23]:
# try it here
A = np.array([[1, 1, 1],
             [0, 0, 1],
             [1, 0, 0]])
connection_difference(A)

-1.3862943611198906

In [24]:
A = np.array([[1, 1, 1],
             [0, 0, 1],
             [1, 0, 0]])
np.testing.assert_almost_equal(connection_difference(A), -1.3862943611198906)

big_matrix = np.array([[0, 1, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1, 1, 0]])
np.testing.assert_almost_equal(connection_difference(big_matrix), -2.8716796248840124)

### Transition probabilities

We can use the adjacency matrix to compute the transition probabilities between nodes. For example, imagine that you are sitting in any node $i$ and you randomly pick one of the edges to go to the next node $j$. We can compute the probability of going to a node $j$ from $i$ as follows and store in a matrix $P$ as follows

$$
P(A) = (\frac{a_{ij}}{\sum_{z=1}^n a_{iz}})_{ij}
$$

For example, for the following adjancy matrix


$$ 
W = \left(\begin{array}{cc}
0 & 1 & 1\\
0 & 0 & 1\\
1 & 1 & 1\\
\end{array}\right)
$$

The matrix $P$ will be

$$
P(W) = \left(\begin{array}{cc}
0 & 1/2 & 1/2\\
0 & 0 & 1\\
1/3 & 1/3 & 1/3\\
\end{array}\right)
$$

Define a function `transition_matrix(A)` that computes the transition matrix as described aboved for adjancency matrix `A`.

**Hint: If you use broadcasting, make sure to `reshape` to match the broadcasting axis correctly**

In [25]:
# 15 points
def transition_matrix(A):
    # YOUR CODE HERE
    n = len(A)
    tA= []
    for i in range(n):
        for j in range(n):
            tA.append(A[i][j]/A[i].sum())
    tA =  np.array(tA)
    tA = tA.reshape(n,n)
    return tA
    #raise NotImplementedError()

In [26]:
W = np.array([[0,1,1],
              [0,0,1],
              [1,1,1]]) 

The result should look like this:

```python
In: transition_matrix(W)
```

```python
Out: array([[ 0.        ,  0.5       ,  0.5       ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.33333333,  0.33333333,  0.33333333]])
```

In [27]:
transition_matrix(W)

array([[ 0.        ,  0.5       ,  0.5       ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.33333333,  0.33333333,  0.33333333]])

In [28]:
W1 = np.array([[1, 0, 0, 1],
             [1, 1, 1, 1],
             [0, 0, 0, 1],
             [0, 0, 1, 0]])
np.testing.assert_almost_equal(transition_matrix(W1), 
                              np.array([[ 0.5 ,  0.  ,  0.  ,  0.5 ],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ]]))

W2 = np.array([[1]])
np.testing.assert_almost_equal(transition_matrix(W2), np.array([[1]]))
another_big_matrix = np.array([[1, 1, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 0, 1, 1]])

np.testing.assert_almost_equal(transition_matrix(another_big_matrix),
        np.array([[ 0.16666667,  0.16666667,  0.16666667,  0.        ,  0.16666667,
         0.16666667,  0.        ,  0.16666667,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ,  0.        ,  0.2       ,  0.        ],
       [ 0.2       ,  0.        ,  0.        ,  0.2       ,  0.        ,
         0.2       ,  0.        ,  0.2       ,  0.2       ,  0.        ],
       [ 0.        ,  0.25      ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.25      ,  0.25      ,  0.25      ],
       [ 0.125     ,  0.        ,  0.125     ,  0.        ,  0.125     ,
         0.125     ,  0.125     ,  0.125     ,  0.125     ,  0.125     ],
       [ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.        ,
         0.        ,  0.        ,  0.        ,  0.33333333,  0.        ],
       [ 0.2       ,  0.        ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.25      ,  0.        ,  0.25      ,  0.25      ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.25      ],
       [ 0.        ,  0.16666667,  0.16666667,  0.16666667,  0.        ,
         0.16666667,  0.16666667,  0.        ,  0.        ,  0.16666667],
       [ 0.        ,  0.16666667,  0.16666667,  0.        ,  0.        ,
         0.16666667,  0.16666667,  0.        ,  0.16666667,  0.16666667]])
                              
                              )
